### ISSUE TITLE
There is already an open DataReader associated with this Command which must be closed first.

### ISSUE THREAD

**Issue by bipin24x7** [skttl/umbraco-unversion#2]
Hi Matt,

Our Umbraco website log files are getting full with below Warning message. It looks like its not executing correctly. Could you please let me know what is the fix?

+++++++++++++++++++++++

2015-06-20 06:39:55,229 [14] WARN  Our.Umbraco.UnVersion.Services.UnVersionService - Executing 
                                    DELETE
                                    FROM    cmsContentVersion
                                    WHERE   contentId = 10220 AND versionId  NOT IN ('7b739e7c-25e0-410f-9bea-4069dadd72e7','a5ccc709-2683-4789-84fd-a055cdf5843c','05e2831c-c6a3-4dfb-9a9b-a3458415c181','20713d80-75e7-455f-b8a4-b16849937232')
System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.
   at System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
   at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Our.Umbraco.UnVersion.Services.UnVersionService.ExecuteSql(String sql, SqlConnection connection)
2015-06-20 06:39:55,229 [14] WARN  Our.Umbraco.UnVersion.Services.UnVersionService - Executing 
                                    DELETE
                                    FROM    cmsDocument 
                                    WHERE   nodeId = 10220 AND versionId  NOT IN ('7b739e7c-25e0-410f-9bea-4069dadd72e7','a5ccc709-2683-4789-84fd-a055cdf5843c','05e2831c-c6a3-4dfb-9a9b-a3458415c181','20713d80-75e7-455f-b8a4-b16849937232')
System.InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.
   at System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
   at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Our.Umbraco.UnVersion.Services.UnVersionService.ExecuteSql(String sql, SqlConnection connection)

++++++++++++++++++++++++++++++++++

Thanks,
Bipin

**Comment by bipin24x7** [comment]
I looked at the forums and it says if you use .ToList() or .Include() in your code then it will solve the problem. I do not have to add "MultipleActiveResultSets=true". Please refer the links below:

http://stackoverflow.com/questions/6062192/there-is-already-an-open-datareader-associated-with-this-command-which-must-be-c

http://stackoverflow.com/questions/18660069/there-is-already-an-open-datareader-that-must-be-closed-first

Can you please help as what should I do?
