### ISSUE TITLE
he DELETE statement conflicted with the REFERENCE constraint "FK_cmsPreviewXml_cmsContentVersion_VersionId".

### ISSUE THREAD

**Issue by bipin24x7** [skttl/umbraco-unversion#3]
I am also getting another error. Please let me know what is the fix for this?

2015-06-20 07:48:24,854 [6] WARN  Our.Umbraco.UnVersion.Services.UnVersionService - Executing 
                                    DELETE
                                    FROM    cmsContentVersion
                                    WHERE   contentId = 10328 AND versionId  NOT IN ('56c2b4fe-b2b9-4733-a2b9-6f6c3161fdb7','2112b8a0-46c5-456b-aca3-649fffb966b8','20fb8136-1cc6-4b4c-abfb-fa8c45decc8c')
System.Data.SqlClient.SqlException (0x80131904): The DELETE statement conflicted with the REFERENCE constraint "FK_cmsPreviewXml_cmsContentVersion_VersionId". The conflict occurred in database "HandymanDB", table "dbo.cmsPreviewXml", column 'versionId'.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Our.Umbraco.UnVersion.Services.UnVersionService.ExecuteSql(String sql, SqlConnection connection)
ClientConnectionId:9cf4abe7-bac1-4f90-bab3-73ce96f1ac81

**Comment by bipin24x7** [comment]
Do you have any updates on this bug?
