### ISSUE TITLE
Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.

### ISSUE THREAD

**Issue by bipin24x7** [skttl/umbraco-unversion#5]
Started getting Timeout errors. Site is working fine and DB connectivity is also good. Only error in log file. Is there any specific settings needs to do?

2015-06-20 08:44:55,957 [41] WARN  Our.Umbraco.UnVersion.Services.UnVersionService - Executing 
                                    DELETE
                                    FROM    cmsPreviewXml
                                    WHERE   nodeId = 10163 AND versionId NOT IN ('5369d999-d528-493b-8e87-59ca09f1920d','1fff9438-bc2b-4674-9398-025b00f3074f','17e6c201-8d3c-438a-b642-db6b5fdabaff','3d207c6c-3024-487c-9f49-2e745203cff4')
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
The statement has been terminated. ---> System.ComponentModel.Win32Exception (0x80004005): Der Wartevorgang wurde abgebrochen
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Our.Umbraco.UnVersion.Services.UnVersionService.ExecuteSql(String sql, SqlConnection connection)
ClientConnectionId:dc17b7b9-b30e-4fb1-91e0-5d7c614d6a8d
Error Number:-2,State:0,Class:11

Thanks,
Bipin

**Comment by bipin24x7** [comment]
![deadlock-issue](https://cloud.githubusercontent.com/assets/8508274/8266419/a840adde-16fb-11e5-947b-a606c46c0e01.JPG)
This tool is creating Deadlock when there is millions of records in the table and website is performing very frequently operation on the database to publish new content.
