### ISSUE TITLE
SQL CE

### ISSUE THREAD

**Issue by kipusoep** [skttl/umbraco-unversion#6]
This plug-in always tries to connect with SQL Server, which gives errors when using SQL CE.

**Comment by mattbrailsford** [comment]
Fixed in commit 63999af544f009840dd4389542e6afe55f6c393c

**Comment by leekelleher** [comment]
Just hit the same error, then when checking the issue tracker - found it had been fixed (in 63999af544f009840dd4389542e6afe55f6c393c) but hasn't been released yet.

Posting error here for google-fu...

**unVersion v2.1.0**


    System.ArgumentException: Keyword not supported: 'flush interval'.
       at System.Data.Common.DbConnectionOptions.ParseInternal(Hashtable parsetable, String connectionString, Boolean buildChain, Hashtable synonyms, Boolean firstKey)
       at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Hashtable synonyms, Boolean useOdbcRules)
       at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
       at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
       at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
       at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
       at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
       at System.Data.SqlClient.SqlConnection..ctor(String connectionString, SqlCredential credential)
       at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
       at Our.Umbraco.UnVersion.Services.UnVersionService.UnVersion(IContent content)
       at Our.Umbraco.UnVersion.Bootstrap.ContentServicePublished(IPublishingStrategy sender, PublishEventArgs`1 e)
       at Umbraco.Core.Events.TypedEventHandler`2.Invoke(TSender sender, TEventArgs e)
       at Umbraco.Core.Events.EventExtensions.RaiseEvent[TSender,TArgs](TypedEventHandler`2 eventHandler, TArgs args, TSender sender)
       at Umbraco.Core.Publishing.PublishingStrategy.PublishingFinalized(IEnumerable`1 content, Boolean isAllRepublished)
       at Umbraco.Core.Services.ContentService.Sort(IEnumerable`1 items, Int32 userId, Boolean raiseEvents)
       at umbraco.presentation.webservices.nodeSorter.SortContent(String[] ids, Int32 parentId)
